### ISSUE TITLE
More descriptive README.md

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#1]
Having a more descriptive README.md with a few instructions about how to contribute to this repo will encourage people to participate and add their robots / controllers.

(Or at least it will lower the entry barriers for potential contributors)

**Comment by jgvictores** [comment]
I put some pictures to give it a more warm feel to it... what did you have in mind?
Maybe a link to a mailing list? One we have or should we begin a new one?
