### ISSUE TITLE
[cmake] Set up cross compiling for raspi

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-robots#11]
[cmake] Set up cross compiling for raspi

help: https://blog.kitware.com/cross-compiling-for-raspberry-pi/

**Comment by David-Estevez** [comment]
More info: http://hackaday.com/2016/09/01/how-to-use-docker-to-cross-compile-for-raspberry-pi-and-more/

**Comment by jgvictores** [comment]
This issue was moved to roboticslab-uc3m/yarp-devices#186
