### ISSUE TITLE
LaserTowerOfDeath resurrection (FW)

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#18]
LaserTowerOfDeath resurrection (FW)

**Comment by jgvictores** [comment]
Started with this at https://github.com/asrob-uc3m/robotDevastation-robots/commit/f5c96582a1b3b2966d89e5a4bcc46a50987bf776
However. @David-Estevez pointed to https://github.com/asrob-uc3m/robotDevastation/releases/tag/dead-newApproach ...must check!

**Comment by jgvictores** [comment]
Currently at https://github.com/asrob-uc3m/robotDevastation-robots/tree/develop/firmware/arduinoServer

**Comment by jgvictores** [comment]
Finished at 8b92d2ca2277314bc19fde20e4be960bb1d7b070
