### ISSUE TITLE
LaserTowerOfDeath resurrection (controller)

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#20]
LaserTowerOfDeath resurrection (controller)

**Comment by jgvictores** [comment]
Working on https://github.com/asrob-uc3m/robotDevastation-robots/tree/develop/libraries/YarpPlugins/RdArduinoClient

**Comment by jgvictores** [comment]
Now at more generic: https://github.com/asrob-uc3m/robotDevastation-robots/tree/develop/libraries/YarpPlugins/RdSerialClient

**Comment by jgvictores** [comment]
Done at a977d8575bf6181f5bed3bdf22b4781ab8d38e7c
