### ISSUE TITLE
Document RD "Ambassator"

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#21]
Document our new robot model RD "Ambassator" (named that way because its made from parts from "Electrónica Embajadores")

- [x] Electronics (and assembly)
- [x] BOM (and finding substitutes)
- [x] Calibration (related to electronics)
- [x] Block diagram
- [x] Add http://wiringpi.com/download-and-install/ as software dependency.

**Comment by David-Estevez** [comment]
@jgvictores would build documentation for this robot go in the [developer manual](https://github.com/asrob-uc3m/robotDevastation-developer-manual) or in the [user manual](https://github.com/asrob-uc3m/robotDevastation-user-manual) ??

**Comment by jgvictores** [comment]
I'd put it in the user manual, as [the closest we have to a user guide](http://asrob.uc3m.es/index.php/C%C3%B3mo_empezar_con_Robot_Devastation) includes instructions for building a robot.
