### ISSUE TITLE
Elipse files uploaded to repo

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#22]
[This file](https://github.com/asrob-uc3m/robotDevastation-robots/blob/develop/.cproject) and [this file](https://github.com/asrob-uc3m/robotDevastation-robots/blob/develop/.project) shouldn't be uploaded to the repo (add to gitignore).

**Comment by PeterBowman** [comment]
Add `.project` as well, both belong to Eclipse (see asrob-uc3m/robotDevastation@107d45f).

**Comment by David-Estevez** [comment]
Thanks for the info, @PeterBowman !

Edited the issue and fixed with the suggested lines in gitignore at f82b948
