### ISSUE TITLE
Remove RDTurret.FCStd1

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-robots#23]
We've added `.FCStd1` (FreeCAD backup) to `.gitignore`, but current 
[RDTurret.FCStd1](https://github.com/asrob-uc3m/robotDevastation-robots/blob/7e8338e49a106cae9a757d55d0c835575541248d/rdturret/RDTurret.FCStd1) should be removed.

**Comment by JuanFdelArco** [comment]
I'd remove it from my local directory and then I did a commit. Is it enough?

**Comment by JuanFdelArco** [comment]
Done

**Comment by jgvictores** [comment]
@JuanFdelArco Thanks!
