### ISSUE TITLE
Rd hardware renewal

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#28]
Decide what hardware has to be bought/replaced.

**Comment by jgvictores** [comment]
1. Router

**Comment by David-Estevez** [comment]
2. Caja ECRO?

**Comment by David-Estevez** [comment]
3. Wheel controller

**Comment by jgvictores** [comment]
> 3. Wheel controller 

Unfortunately, I believe ECRO wheel controller is only sold within a 2-wheel kit https://www.parallax.com/product/28962

**Comment by jgvictores** [comment]
Related: https://github.com/asrob-uc3m/impresoras-asrob/issues/56

**Comment by jgvictores** [comment]
Router is WIP at https://github.com/asrob-uc3m/impresoras-asrob/issues/56, general topic not very hot at the moment (working on "revival" issues).
