### ISSUE TITLE
Document robot software development on the developer manual

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#31]
The Developer Manual is quite complete software-wise, but lacks documentation about the software contained in this repo. This is mainly due to the fact that the author of most part of this repo is @jgvictores .

I think it would be very nice to have all the wonderful software contained in this repo documented in the Developer Manual. What do you think, @jgvictores ?

**Comment by jgvictores** [comment]
Makes sense. :smile:

**Comment by jgvictores** [comment]
This issue was moved to asrob-uc3m/robotDevastation-developer-manual#9
