### ISSUE TITLE
Merge IRobotManager moveForward/moveBackwards and similar pairs?

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/robotDevastation-robots#42]
Merge [IRobotManager](https://github.com/asrob-uc3m/robotDevastation-robots/blob/e743adcfc864481e0a54918f02ae0c62f77b0d40/libraries/YarpPlugins/IRobotManager.hpp#L22-L23) `moveForward()`/`moveBackwards()` and similar pairs?

Move, turn, pan, tilt all get (signed) ints as signature. Could be merged to reduce the functions.

PS: I'd go for `double` rather than `int`, and document units (e.g. attempt `m/s` rather than undocumented notion of percentage).

**Comment by PeterBowman** [comment]
This issue was moved to asrob-uc3m/yarp-devices#4
