### ISSUE TITLE
WiringPi library about to be deprecated

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/robotDevastation-robots#48]
FYI: https://hackaday.com/2019/09/18/wiringpi-library-to-be-deprecated/

**Comment by jgvictores** [comment]
@David-Estevez Thanks for the info!

**Comment by PeterBowman** [comment]
Pity we never forked git://git.drogon.net/wiringPi into the asrob-uc3m org, I would do that as soon as the server is up again.

**Comment by PeterBowman** [comment]
@jgvictores found a local clone of drogon.net (last commit: March 2017), now it lives in our org at https://github.com/asrob-uc3m/wiringPi.

Next, I'm going to unbreak Travis jobs by fetching these sources instead.

**Comment by PeterBowman** [comment]
> Next, I'm going to unbreak Travis jobs by fetching these sources instead.

Done at https://github.com/asrob-uc3m/yarp-devices/commit/44921d4ad9fe707d36ee03693d9293b0f17e9332.

**Comment by jgvictores** [comment]
Updated in our install doc at https://github.com/asrob-uc3m/yarp-devices/commit/7b3411f594dbaa288470811ffdf17021135c0785
