### ISSUE TITLE
RD3 and RDTurret (...and other ideas)

### ISSUE THREAD

**Issue by JuanFdelArco** [asrob-uc3m/robotDevastation-robots#7]
New robot design assigned to Juan F. del Arco.

**Comment by David-Estevez** [comment]
@JuanFdelArco when you are more o less done with the design of the new RDTurret I can help you setup a stereo camera to have a 3D First Person View of the Turret's point of view with a phone (and old project of mine) :smile:

**Comment by JuanFdelArco** [comment]
Idea nº1: (W.I.P.)
- Omnidirectional robot. 
- There are QR's on each corner.
- It can be combined with RDTurret for two players on one robot.

![idea 1](https://cloud.githubusercontent.com/assets/17598605/14489586/6bec5e6a-016e-11e6-9e6f-dd815651cf7e.jpg)

**Comment by David-Estevez** [comment]
@JuanFdelArco Very cool robot!!

**Comment by David-Estevez** [comment]
Suggestion for the wheels: 
- http://www.robotshop.com/en/58mm-plastic-omni-wheel-lego-nxt-servo.html
- http://www.robotshop.com/en/48mm-omniwheel-lego-nxt-servo.html

**Comment by David-Estevez** [comment]
Looking for "robot tracks" in aliexpress: http://es.aliexpress.com/store/product/Free-shipping-smart-Car-Smart-Car-Chassis-Robot-Tracking-Sensor-Coded-Disc/1460814_32288410589.html

**Comment by David-Estevez** [comment]
More ideas: use stock batteries from consumer electronics products (such as cameras, smartphones, etc) 

Example: http://es.aliexpress.com/store/product/2pcs-Battery-Charger-7-4V-1800mAh-EN-EL9-EN-EL9-ENEL9-Rechargeable-Camera-Battery-For-Nikon/1163277_1797911243.html

**Comment by David-Estevez** [comment]
Even more ideas: [Cool Fighting Robots](https://www.youtube.com/watch?v=BgOG5te3jlc) via @JavierIH 

(Maybe all this info should be moved to [robotDevastation-research](https://github.com/asrob-uc3m/robotDevastation-research))

**Comment by jgvictores** [comment]
This issue was moved to asrob-uc3m/robotDevastation-research#10
